
package ufrrj.bruno.ia.Telas;

import java.awt.Color;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.JFrame;
import ufrrj.bruno.ia.Mundo;
import ufrrj.bruno.ia.celulas.Comum;
import ufrrj.bruno.ia.celulas.Invasor;
import ufrrj.bruno.ia.graficos.Fatia;
import ufrrj.bruno.ia.graficos.GraficoPizza;

public class Tela extends javax.swing.JFrame {

    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelVisual = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Imunológico Artificial");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                redimensiona(evt);
            }
        });

        painelVisual.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout painelVisualLayout = new javax.swing.GroupLayout(painelVisual);
        painelVisual.setLayout(painelVisualLayout);
        painelVisualLayout.setHorizontalGroup(
            painelVisualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        painelVisualLayout.setVerticalGroup(
            painelVisualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jMenu1.setText("Novo");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novo(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Editar");
        jMenuBar1.add(jMenu3);

        jMenu2.setText("Inserir");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insere(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Estatisticas");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abreEstatisticas(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelVisual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelVisual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        painelVisual.getAccessibleContext().setAccessibleName("");
        painelVisual.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Mundo mundo;
    Visual visual = null;
    Image fundo = Toolkit.getDefaultToolkit().createImage(getClass().getResource("/img/blood.jpg"));
    private void novo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novo
        //MATAR as threads
        if(mundo != null){
           return;
//           for(Celula celula : mundo.getCelulas()){
//                celula.ativa = false;
//                celula = null;
//                //celula.mundo = null;
//            } 
        }
        mundo = null;
        //CRIA NOVO
//        painelVisual.getGraphics().drawImage(fundo, 0, 0, painelVisual);
//        painelVisual.repaint();
//        painelVisual.add(new JLabel(new ImageIcon(getClass().getResource("/img/blood.jpg"))));
//        this.repaint();
        mundo = new Mundo(getWidth(),getHeight());
        visual = new Visual(mundo);
        visual.setSize(getWidth(),getHeight());
        painelVisual.add(visual);
        
    }//GEN-LAST:event_novo

    private void redimensiona(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_redimensiona
        if(visual != null) { visual.setSize(getWidth(),getHeight()); mundo.redimensiona(getWidth(), getHeight());}
    }//GEN-LAST:event_redimensiona

    private void insere(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insere
        mundo.adicionaCelula(new Invasor(mundo));
    }//GEN-LAST:event_insere

    private void abreEstatisticas(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abreEstatisticas
        if(mundo == null){ return; }
        JFrame tela = new JFrame("Estatisticas");
        Estatisticas e = new Estatisticas(mundo);
        tela.setSize(300,600);
        e.setSize(tela.getSize());

        GraficoPizza grafico = new GraficoPizza(mundo,new Rectangle(50,40,200,200));
        //grafico.setSize(200,200);
        tela.add(e);
        tela.add(grafico);     
        
        tela.setVisible(true);
    }//GEN-LAST:event_abreEstatisticas

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel painelVisual;
    // End of variables declaration//GEN-END:variables
}
